name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up commit SHA
        id: vars
        run: echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER}}
          password: ${{ secrets.DOCKER_TOKEN}}
      -
        name: Set up Docker Buildx
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jmartinezblanco/front:${{ env.COMMIT_SHA }}